### ISSUE TITLE
見本の完成

### ISSUE THREAD

**Issue by neila** [unchain-tech/Solana-dApp#1]
見本としてこのレポジトリが完成していて、学習コンテンツにその開発方法が反映されている

**Comment by neila** [comment]
`complete` ブランチにとりあえず自分の漕ぎ着いたとこまで入れました。ほぼ一通り安定して動く状態です。あと動いていないのが以下の一点あるのですが、根本的な問題ではなさそうです 🙏🏽 。

ちょっと作業離れなくてはいけなくて、投げやりで申し訳ないのですが、いじってみて、完成まで持っていけるかみてみてください @yk-saito  :bow:

未着手/未完箇所
- ブラウザ側からProviderを呼び出し接続する際の安定する挙動（なんか現状yarn startすると `Provider` が存在しないだのなんだの言われる。あるのに.. ）

環境
- rustc 1.68.2
- solana 1.16.0
- anchor 0.26.0

**Comment by honganji** [comment]
見本は完成したのでcloseします。
