### ISSUE TITLE
starter projectの追加

### ISSUE THREAD

**Issue by neila** [unchain-tech/Solana-dApp#2]
- 別ブランチに追加。
- 該当ブランチからクローンするよう、学習コンテンツを修正

**Comment by neila** [comment]
rustのセットアップとか色々混乱ポイント多かったので最低限必要なファイルをstarterに入れました。version適合、動作確認済です。再現確認いただいたらcloseいただいてokです

**Comment by honganji** [comment]
再現確認できたのでcloseさせていただきます
